### ISSUE TITLE
Modifying default test cases

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/rtandroid_packages_apps_Benchmark#4]
1) Check the size of the label "Name". It seems to be smaller than "Priority".

2) "Core Lock" is set to "disabled" by default. Even after a change.

**Comment by SirNoahFell** [comment]
Done.
(in my branch)

**Comment by ikalkov** [comment]
@SirNoahFell You should use "fixes #?" tags in your commit messages to reference and close issues automatically.
